<x-app-layout>
    <x-slot name="header"><div><p class="casa-section-label">{{ __('Admin module') }}</p><h1 class="mt-2 font-display text-3xl font-black text-casa-text">{{ __('Add-ons') }}</h1><p class="mt-2 text-sm text-casa-muted">{{ __('Maintain shared booking extras, pricing, duration, and availability.') }}</p></div><a href="{{ route('admin.addons.create') }}" class="casa-button-primary">{{ __('Add add-on') }}</a></x-slot>
    <x-app-card>
        <x-list-toolbar eyebrow="{{ __('Catalog') }}" title="{{ __('Add-on list') }}" :count="$addons->total()" :reset-url="route('admin.addons.index')" :active-filters="collect(request()->only(['q', 'status']))->filter(fn ($value) => filled($value))->count()" :collapsible="true">
            <form method="GET" action="{{ route('admin.addons.index') }}" class="casa-filter-grid sm:grid-cols-[minmax(12rem,1fr)_auto_auto]"><input type="search" name="q" value="{{ $search }}" class="casa-input" placeholder="{{ __('Search add-ons') }}" aria-label="{{ __('Search add-ons') }}"><select name="status" class="casa-input"><option value="">{{ __('All statuses') }}</option><option value="active" @selected($status === 'active')>{{ __('Active') }}</option><option value="inactive" @selected($status === 'inactive')>{{ __('Inactive') }}</option></select><button class="casa-button-secondary">{{ __('Filter') }}</button></form>
        </x-list-toolbar>
        <div class="mt-5"><x-table-shell><thead class="bg-casa-bg text-left text-xs font-black uppercase tracking-[0.1em] text-casa-muted"><tr><th class="px-4 py-3">{{ __('Add-on') }}</th><th class="px-4 py-3">{{ __('Duration') }}</th><th class="px-4 py-3">{{ __('Price') }}</th><th class="px-4 py-3">{{ __('Status') }}</th><th class="px-4 py-3">{{ __('Actions') }}</th></tr></thead><tbody class="divide-y divide-casa-border text-sm">@forelse ($addons as $addon)<tr><td class="px-4 py-4"><a href="{{ route('admin.addons.edit', $addon) }}" class="font-bold text-casa-primary">{{ $addon->name }}</a><p class="mt-1 text-xs text-casa-muted">{{ $addon->code }}</p><p class="mt-1 text-xs text-casa-muted">{{ $addon->description }}</p></td><td class="px-4 py-4">{{ $addon->duration_minutes }} {{ __('min') }}</td><td class="px-4 py-4 font-semibold">PHP {{ number_format((float) $addon->price, 2) }}</td><td class="px-4 py-4"><x-status-badge :tone="$addon->is_active ? 'success' : 'dark'">{{ $addon->is_active ? __('Active') : __('Inactive') }}</x-status-badge></td><td class="px-4 py-4"><div class="flex flex-wrap gap-2"><a href="{{ route('admin.addons.edit', $addon) }}" class="font-bold text-casa-primary">{{ __('Edit') }}</a><x-confirm-action :action="route('admin.addons.toggle', $addon)" method="PATCH" :label="$addon->is_active ? __('Deactivate') : __('Activate')" :confirm-title="$addon->is_active ? __('Deactivate add-on?') : __('Activate add-on?')" :confirm-message="$addon->is_active ? __('It will no longer be offered for new bookings.') : __('It will be available for new bookings.')" :confirm-button="$addon->is_active ? __('Deactivate') : __('Activate')" /></div></td></tr>@empty<tr><td colspan="5" class="px-4 py-8 text-center text-casa-muted">{{ __('No add-ons found.') }}</td></tr>@endforelse</tbody></x-table-shell><div class="mt-5">{{ $addons->links() }}</div></div>
    </x-app-card>
</x-app-layout>
