<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import QrcodeVue from 'qrcode.vue'
import { attendanceQr, confirmAttendanceScan, pendingAttendanceScans, rejectAttendanceScan, type AttendanceScan } from '../lib/api'
const qr=ref<{payload:string;expires_at:string}|null>(null), scans=ref<AttendanceScan[]>([]), error=ref(''), busy=ref(false), seconds=ref(60);let timer:ReturnType<typeof setInterval>|undefined
async function refresh(){try{qr.value=await attendanceQr();scans.value=await pendingAttendanceScans();seconds.value=Math.max(1,Math.ceil((new Date(qr.value.expires_at).getTime()-Date.now())/1000))}catch{error.value='Attendance station could not refresh.'}}
async function resolve(id:number,action?:'time_in'|'time_out'){busy.value=true;try{if(action)await confirmAttendanceScan(id,action);else await rejectAttendanceScan(id);await refresh()}catch{error.value='The attendance scan could not be resolved.'}finally{busy.value=false}}
const countdown=computed(()=>`${Math.floor(seconds.value/60)}:${String(seconds.value%60).padStart(2,'0')}`)
onMounted(async()=>{await refresh();timer=setInterval(async()=>{if(qr.value)seconds.value=Math.max(0,Math.ceil((new Date(qr.value.expires_at).getTime()-Date.now())/1000));if(seconds.value===0)await refresh();else scans.value=await pendingAttendanceScans().catch(()=>scans.value)},5000)});onBeforeUnmount(()=>{if(timer)clearInterval(timer)})
</script>
<template><section class="station"><header><p class="eyebrow">ATTENDANCE STATION</p><h2>Therapist check-in</h2><p>Show this live code, verify the therapist, then choose their action.</p></header><p v-if="error" class="alert">{{error}}</p><div v-if="qr" class="qr"><QrcodeVue :value="qr.payload" :size="220" level="H" aria-label="Therapist attendance check-in QR code"/><strong>Refreshes in {{countdown}}</strong></div><div class="queue"><h3>Pending verification</h3><p v-if="!scans.length">No therapist scans awaiting review.</p><article v-for="scan in scans" :key="scan.id"><strong>{{scan.therapist?.name}}</strong><small>Scanned {{new Date(scan.scanned_at??'').toLocaleTimeString()}}</small><div><button :disabled="busy" @click="resolve(scan.id,'time_in')">Time in</button><button :disabled="busy" @click="resolve(scan.id,'time_out')">Time out</button><button :disabled="busy" class="reject" @click="resolve(scan.id)">Reject</button></div></article></div></section></template>
<style scoped>.station{margin-top:1rem;padding:1rem;border:1px solid var(--casa-border);border-radius:1rem;background:var(--casa-paper)}h2,h3{font-family:var(--font-display);color:var(--casa-deep-palm)}.qr{display:grid;justify-items:center;gap:.75rem;padding:1rem;background:#fff;border-radius:.75rem}.queue{display:grid;gap:.65rem;margin-top:1rem}.queue article{display:grid;gap:.35rem;padding:.75rem;border:1px solid var(--casa-border);border-radius:.75rem}.queue small{color:var(--casa-muted)}.queue div{display:flex;gap:.4rem;flex-wrap:wrap}.queue button{min-height:40px;border:0;border-radius:.5rem;background:var(--casa-deep-palm);color:#fff;padding:0 .75rem;font-weight:700}.queue .reject{background:#7a3e14}</style>
