import { defineStore } from 'pinia'
import { ref } from 'vue'
import {
  adminCommissions, adminFeedback, adminPromotions, adminReports, adminSettings, adminUsers, apiError,
  createAdminUser, dismissAdminPromotion, payAdminCommission, updateAdminPromotionSettings, updateAdminSettings, updateAdminUser,
  type AdminCommission, type AdminFeedbackOverview, type AdminPromotion, type AdminPromotionPreset, type AdminReport, type AdminSettings, type AdminUserAccess, type AppointmentParty, type StaffFeedback,
} from '../lib/api'
import { shareAdminReport } from '../lib/reportExport'
import { hasMobileData, invalidateMobileData, loadMobileData, OPERATIONAL_TTL_MS, REFERENCE_TTL_MS } from '../lib/mobileDataCache'
const emptyMeta=()=>({current_page:1,last_page:1,per_page:15,total:0,from:null as number|null,to:null as number|null})
export const useAdminInsightsStore=defineStore('adminInsights',()=>{
  const feedback=ref<StaffFeedback[]>([]);const feedbackSummary=ref({positive:0,neutral:0,negative:0});const feedbackOverview=ref<AdminFeedbackOverview|null>(null);const feedbackMeta=ref(emptyMeta());const feedbackSentiment=ref('');const feedbackSearch=ref('');const feedbackDateFrom=ref('');const feedbackDateTo=ref('');const feedbackTopic=ref('')
  const commissions=ref<AdminCommission[]>([]);const commissionSummary=ref({pending:'0.00',paid:'0.00',net:'0.00'});const commissionStaff=ref<AppointmentParty[]>([]);const commissionMeta=ref(emptyMeta());const commissionStatus=ref('');const commissionStaffId=ref<number|undefined>()
  const promotions=ref<AdminPromotion[]>([]);const promotionSummary=ref({available:0,reserved:0,used:0,expired:0,dismissed:0});const promotionMeta=ref(emptyMeta());const promotionLifecycle=ref('');const promotionSearch=ref('');const promotionPresets=ref<AdminPromotionPreset[]>([]);const promotionAddons=ref<Array<{code:string;name:string}>>([]);const promotionValidity=ref<number|null>(null);const promotionValidityOptions=ref<number[]>([])
  const report=ref<AdminReport|null>(null);const reportType=ref('appointments');const reportSearch=ref('');const reportDateFrom=ref('');const reportDateTo=ref('')
  const settings=ref<AdminSettings|null>(null);const users=ref<AdminUserAccess[]>([]);const userRoles=ref<string[]>([]);const userMeta=ref(emptyMeta())
  const loading=ref(false);const refreshing=ref(false);const working=ref(false);const error=ref('');const notice=ref('');const fields=ref<Record<string,string[]>>({})
  const feedbackKey=(page=1)=>`admin:feedback:${page}:${feedbackSentiment.value}:${feedbackSearch.value.trim()}:${feedbackDateFrom.value}:${feedbackDateTo.value}:${feedbackTopic.value}`;const commissionsKey=(page=1)=>`admin:commissions:${page}:${commissionStatus.value}:${commissionStaffId.value??''}`;const promotionsKey=(page=1)=>`admin:promotions:${page}:${promotionLifecycle.value}:${promotionSearch.value.trim()}`;const reportKey=(page=1)=>`admin:report:${page}:${reportType.value}:${reportSearch.value.trim()}:${reportDateFrom.value}:${reportDateTo.value}`
  const hasFeedback=(page=1)=>hasMobileData(feedbackKey(page));const hasCommissions=(page=1)=>hasMobileData(commissionsKey(page));const hasPromotions=(page=1)=>hasMobileData(promotionsKey(page));const hasReport=(page=1)=>hasMobileData(reportKey(page))
  async function loadFeedback(page=1,force=false):Promise<void>{await runCached(feedbackKey(page),OPERATIONAL_TTL_MS,async()=>{const r=await adminFeedback({page,sentiment:feedbackSentiment.value||undefined,q:feedbackSearch.value.trim()||undefined,date_from:feedbackDateFrom.value||undefined,date_to:feedbackDateTo.value||undefined,topic:feedbackTopic.value||undefined});feedback.value=r.data;feedbackSummary.value=r.summary;feedbackOverview.value=r.overview;feedbackMeta.value=r.meta},force)}
  async function loadCommissions(page=1,force=false):Promise<void>{await runCached(commissionsKey(page),OPERATIONAL_TTL_MS,async()=>{const r=await adminCommissions({page,status:commissionStatus.value||undefined,staff_profile_id:commissionStaffId.value});commissions.value=r.data;commissionSummary.value=r.summary;commissionStaff.value=r.staff;commissionMeta.value=r.meta},force)}
  async function payCommission(id:number,paid_at:string,notes=''):Promise<boolean>{return mutate(()=>payAdminCommission(id,{paid_at,notes}),()=>{invalidateMobileData('admin:');return loadCommissions(commissionMeta.value.current_page,true)})}
  async function loadPromotions(page=1,force=false):Promise<void>{await runCached(promotionsKey(page),OPERATIONAL_TTL_MS,async()=>{const r=await adminPromotions({page,lifecycle:promotionLifecycle.value||undefined,q:promotionSearch.value.trim()||undefined});promotions.value=r.data;promotionSummary.value=r.summary;promotionMeta.value=r.meta;promotionPresets.value=r.presets;promotionAddons.value=r.addons;promotionValidity.value=r.settings.promotion_voucher_validity_days;promotionValidityOptions.value=r.settings.validity_options},force)}
  async function dismissPromotion(id:number):Promise<boolean>{return mutate(()=>dismissAdminPromotion(id),()=>{invalidateMobileData('admin:');return loadPromotions(promotionMeta.value.current_page,true)})}
  async function savePromotionSettings(payload:Record<string,unknown>):Promise<boolean>{return mutate(()=>updateAdminPromotionSettings(payload),()=>{invalidateMobileData('admin:');return loadPromotions(1,true)})}
  async function loadReport(page=1,force=false):Promise<void>{await runCached(reportKey(page),OPERATIONAL_TTL_MS,async()=>{report.value=await adminReports({page,type:reportType.value,q:reportSearch.value.trim()||undefined,date_from:reportDateFrom.value||undefined,date_to:reportDateTo.value||undefined})},force)}
  async function shareReport():Promise<boolean>{working.value=true;clear();try{const filename=await shareAdminReport(reportType.value,{q:reportSearch.value.trim()||undefined,date_from:reportDateFrom.value||undefined,date_to:reportDateTo.value||undefined});notice.value=`${filename} is ready to share.`;return true}catch(reason){capture(reason);return false}finally{working.value=false}}
  async function loadSettings(force=false):Promise<void>{await runCached('admin:settings',REFERENCE_TTL_MS,async()=>{settings.value=await adminSettings()},force)}
  async function saveSettings(payload:Record<string,unknown>):Promise<boolean>{return mutate(()=>updateAdminSettings(payload),()=>{invalidateMobileData('admin:settings');return loadSettings(true)})}
  async function loadUsers(page=1,force=false):Promise<void>{await runCached(`admin:users:${page}`,OPERATIONAL_TTL_MS,async()=>{const r=await adminUsers(page);users.value=r.data;userRoles.value=r.roles;userMeta.value=r.meta},force)}
  async function saveUser(payload:Record<string,unknown>,id?:number):Promise<boolean>{return mutate(()=>id?updateAdminUser(id,payload):createAdminUser(payload),()=>{invalidateMobileData('admin:users');return loadUsers(id?userMeta.value.current_page:1,true)})}
  let initialRequests=0;let refreshRequests=0
  async function runCached(key:string,ttl:number,task:()=>Promise<void>,force=false):Promise<void>{const initial=!hasMobileData(key);if(initial){initialRequests++;loading.value=true}else{refreshRequests++;refreshing.value=true}clear();try{await loadMobileData(key,ttl,task,force)}catch(reason){capture(reason)}finally{if(initial){initialRequests--;loading.value=initialRequests>0}else{refreshRequests--;refreshing.value=refreshRequests>0}}}
  async function mutate(task:()=>Promise<{message:string}>,refresh:()=>Promise<void>):Promise<boolean>{working.value=true;clear();try{const r=await task();await refresh();notice.value=r.message;return true}catch(reason){capture(reason);return false}finally{working.value=false}}
  function clear():void{error.value='';notice.value='';fields.value={}}
  function capture(reason:unknown):void{const failure=apiError(reason);error.value=failure.message;fields.value=failure.fields??{}}
  function reset():void{feedback.value=[];feedbackSummary.value={positive:0,neutral:0,negative:0};feedbackOverview.value=null;feedbackMeta.value=emptyMeta();commissions.value=[];commissionSummary.value={pending:'0.00',paid:'0.00',net:'0.00'};commissionMeta.value=emptyMeta();promotions.value=[];promotionSummary.value={available:0,reserved:0,used:0,expired:0,dismissed:0};promotionMeta.value=emptyMeta();report.value=null;settings.value=null;users.value=[];userRoles.value=[];userMeta.value=emptyMeta();feedbackSentiment.value='';feedbackSearch.value='';feedbackDateFrom.value='';feedbackDateTo.value='';feedbackTopic.value='';commissionStatus.value='';commissionStaffId.value=undefined;promotionLifecycle.value='';promotionSearch.value='';clear()}
  return{feedback,feedbackSummary,feedbackOverview,feedbackMeta,feedbackSentiment,feedbackSearch,feedbackDateFrom,feedbackDateTo,feedbackTopic,commissions,commissionSummary,commissionStaff,commissionMeta,commissionStatus,commissionStaffId,promotions,promotionSummary,promotionMeta,promotionLifecycle,promotionSearch,promotionPresets,promotionAddons,promotionValidity,promotionValidityOptions,report,reportType,reportSearch,reportDateFrom,reportDateTo,settings,users,userRoles,userMeta,loading,refreshing,working,error,notice,fields,hasFeedback,hasCommissions,hasPromotions,hasReport,loadFeedback,loadCommissions,payCommission,loadPromotions,dismissPromotion,savePromotionSettings,loadReport,shareReport,loadSettings,saveSettings,loadUsers,saveUser,clear,reset}
})
