<?php

return [
    'business_name' => 'Casa Paraiso Body and Wellness Spa',
    'marketing_line' => 'Reserve your spot. You deserve this.',
    'pagination' => [
        'per_page' => 15,
    ],
    'commissions' => [
        'therapist_rate' => 0.22,
    ],
    'security' => [
        'force_https' => (bool) env('FORCE_HTTPS', false),
        'hsts' => (bool) env('HSTS_ENABLED', false),
        'trusted_hosts' => array_values(array_filter(array_map(
            'trim',
            explode(',', (string) env('TRUSTED_HOSTS', '')),
        ))),
    ],
    'mobile' => [
        'service' => 'casa-paraiso-mobile-api',
        'api_version' => 'v1',
        'pairing_protocol' => 1,
        'instance_id' => env('MOBILE_DEMO_INSTANCE_ID'),
        'demo_enabled' => (bool) env('MOBILE_DEMO_PAIRING_ENABLED', false),
        'pairing_cache_store' => env('MOBILE_PAIRING_CACHE_STORE', 'file'),
        'pairing_ttl_seconds' => 300,
        'token_ttl_days' => 30,
    ],
    'business_hours' => [
        'summary' => 'Open every day',
        'window' => '1:00 PM to 12:00 MN',
        'timezone' => 'Asia/Manila',
        'opens_at' => '13:00',
        'closes_at' => '00:00',
        'closes_next_day' => true,
        'slot_interval_minutes' => 30,
        'customer_booking_lead_time_minutes' => 30,
    ],
    'service_packages' => [
        [
            'name' => 'GAIA TOUCH',
            'slug' => 'gaia-touch',
            'description' => 'Signature Full Body Massage with Swedish, Shiatsu, and Traditional Hilot techniques.',
            'duration_minutes' => 60,
            'duration_label' => '1 Hour',
            'price' => 499.00,
            'includes' => [
                'Signature Full Body Massage',
                'Swedish',
                'Shiatsu',
                'Traditional Hilot',
            ],
        ],
        [
            'name' => 'TETHYS FLOW',
            'slug' => 'tethys-flow',
            'description' => 'Signature Full Body Massage with Ventosa or Hot Compress add-on options.',
            'duration_minutes' => 60,
            'duration_label' => '1 Hour',
            'price' => 649.00,
            'includes' => [
                'Signature Full Body Massage',
                'Ventosa',
                'Hot Compress',
            ],
        ],
        [
            'name' => 'HESTIA WARMTH',
            'slug' => 'hestia-warmth',
            'description' => 'Full Body Massage with warming add-on options for deeper body relief.',
            'duration_minutes' => 90,
            'duration_label' => '1 Hour 30 Minutes',
            'price' => 749.00,
            'includes' => [
                'Full Body Massage',
                'Ventosa',
                'Hot Stone',
                'Hot Compress',
            ],
        ],
        [
            'name' => 'AURORA BREEZE',
            'slug' => 'aurora-breeze',
            'description' => 'Extended Full Body Massage package with add-ons and VIP Room access.',
            'duration_minutes' => 120,
            'duration_label' => '2 Hours',
            'price' => 849.00,
            'includes' => [
                'Full Body Massage',
                'Ventosa',
                'Hot Compress',
                'Hot Stone',
                'VIP Room',
            ],
        ],
    ],
    'addons' => [
        [
            'code' => 'ventosa',
            'name' => 'Ventosa',
            'price' => 200.00,
            'duration_minutes' => 0,
        ],
        [
            'code' => 'hot-compress',
            'name' => 'Hot Compress',
            'price' => 200.00,
            'duration_minutes' => 0,
        ],
        [
            'code' => 'hot-stone',
            'name' => 'Hot Stone',
            'price' => 200.00,
            'duration_minutes' => 0,
        ],
        [
            'code' => 'back-massage-30',
            'name' => '30-Minute Back Massage',
            'price' => 299.00,
            'duration_minutes' => 30,
        ],
        [
            'code' => 'vip-room',
            'name' => 'VIP Room',
            'price' => 200.00,
            'duration_minutes' => 0,
        ],
    ],
    'customer_rewards' => [
        'default_validity_days' => 90,
        'validity_options' => [30, 60, 90, 180],
        'presets' => [
            [
                'key' => 'high_value',
                'name' => 'High-value customer',
                'description' => 'Three or more paid visits in the last 90 days with at least PHP 5,000 spent.',
                'recency_min_days' => null,
                'recency_max_days' => 90,
                'frequency_min' => 3,
                'frequency_max' => null,
                'monetary_min' => 5000,
                'monetary_max' => null,
                'addon_code' => 'vip-room',
            ],
            [
                'key' => 'loyal',
                'name' => 'Loyal customer',
                'description' => 'Four or more paid visits in the last 60 days.',
                'recency_min_days' => null,
                'recency_max_days' => 60,
                'frequency_min' => 4,
                'frequency_max' => null,
                'monetary_min' => null,
                'monetary_max' => null,
                'addon_code' => 'back-massage-30',
            ],
            [
                'key' => 'at_risk',
                'name' => 'At-risk customer',
                'description' => 'Two or more paid visits, with the last visit 61 to 180 days ago.',
                'recency_min_days' => 61,
                'recency_max_days' => 180,
                'frequency_min' => 2,
                'frequency_max' => null,
                'monetary_min' => null,
                'monetary_max' => null,
                'addon_code' => 'ventosa',
            ],
            [
                'key' => 'inactive',
                'name' => 'Inactive customer',
                'description' => 'At least one paid visit, with the last visit 181 days ago or more.',
                'recency_min_days' => 181,
                'recency_max_days' => null,
                'frequency_min' => 1,
                'frequency_max' => null,
                'monetary_min' => null,
                'monetary_max' => null,
                'addon_code' => 'hot-stone',
            ],
            [
                'key' => 'new_customer',
                'name' => 'New customer',
                'description' => 'One paid visit completed within the last 30 days.',
                'recency_min_days' => null,
                'recency_max_days' => 30,
                'frequency_min' => 1,
                'frequency_max' => 1,
                'monetary_min' => null,
                'monetary_max' => null,
                'addon_code' => 'hot-compress',
            ],
        ],
    ],
];
