<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{useAuthStore}from'../stores/auth';import{useAdminInsightsStore}from'../stores/adminInsights';import type{AdminUserAccess}from'../lib/api';
const auth=useAuthStore();const store=useAdminInsightsStore();const tab=ref<'settings'|'users'>('settings');const userOpen=ref(false);const editing=ref<AdminUserAccess|null>(null)
const business=reactive({business_name:'',contact_email:'',contact_phone:'',business_address:'',location_landmarks:'',facebook_url:'',messenger_url:'',map_url:'',default_payment_method:''});const userForm=reactive({name:'',email:'',role:'customer',is_active:true})
onMounted(async()=>{await store.loadSettings();if(store.settings)Object.assign(business,store.settings.settings);if(auth.user?.role==='super_admin')await store.loadUsers()})
function editUser(user?:AdminUserAccess):void{editing.value=user??null;Object.assign(userForm,{name:user?.name??'',email:user?.email??'',role:user?.role??'customer',is_active:user?.is_active??true});store.clear();userOpen.value=true}
async function saveUser():Promise<void>{if(await store.saveUser({...userForm},editing.value?.id))userOpen.value=false}
</script>
<template><section class="page"><header><p class="eyebrow">BUSINESS CONTROL</p><h1>Settings & access</h1><p>Maintain public business details, operating defaults, release readiness, and protected user access.</p></header><nav v-if="auth.user?.role==='super_admin'" class="switch"><button :class="{active:tab==='settings'}" @click="tab='settings'">Settings</button><button :class="{active:tab==='users'}" @click="tab='users'">User access</button></nav><p v-if="store.notice" class="notice">{{store.notice}}</p><p v-if="store.error" class="alert">{{store.error}}</p>
<section v-if="tab==='settings'&&store.settings"><form class="editor" @submit.prevent="store.saveSettings({...business})"><label>Business name<input v-model="business.business_name" required></label><label>Contact email<input v-model="business.contact_email" type="email"></label><label>Contact phone<input v-model="business.contact_phone"></label><label>Business address<textarea v-model="business.business_address" rows="3"/></label><label>Location landmarks<textarea v-model="business.location_landmarks" rows="3"/></label><label>Messenger link<input v-model="business.messenger_url" type="url"></label><label>Facebook page link<input v-model="business.facebook_url" type="url"></label><label>Google Maps link<input v-model="business.map_url" type="url"></label><label>Default payment method<select v-model="business.default_payment_method"><option v-for="method in store.settings.payment_methods" :key="method">{{method}}</option></select></label><button class="primary" :disabled="store.working">Save business settings</button></form><section class="read-only"><h2>Fixed operating safeguards</h2><p>Asia/Manila · {{store.settings.operating.opens_at}} to midnight · {{store.settings.operating.slot_interval_minutes}}-minute starts</p><p>{{Number(store.settings.operating.commission_rate)*100}}% therapist commission</p></section><section class="read-only"><h2>Security readiness</h2><article v-for="check in store.settings.security" :key="check.label"><span>{{check.label}}</span><strong :class="check.ready?'ready':'review'">{{check.value}}</strong></article></section></section>
<section v-else-if="tab==='users'"><button class="primary" @click="editUser()">Create user access</button><div class="list"><button v-for="user in store.users" :key="user.id" class="card" :disabled="user.protected" @click="editUser(user)"><div class="top"><strong>{{user.name}}</strong><span>{{user.is_active?'Active':'Inactive'}}</span></div><p>{{user.email}}</p><small>{{user.role.replace('_',' ')}} · {{user.google_linked?'Google linked':'Local setup'}}</small><em v-if="user.protected">Protected account</em></button></div><div class="pager" v-if="store.userMeta.last_page>1"><button :disabled="store.userMeta.current_page===1" @click="store.loadUsers(store.userMeta.current_page-1)">Previous</button><span>Page {{store.userMeta.current_page}} of {{store.userMeta.last_page}}</span><button :disabled="store.userMeta.current_page===store.userMeta.last_page" @click="store.loadUsers(store.userMeta.current_page+1)">Next</button></div></section>
<section v-if="userOpen" class="sheet"><header><div><p class="eyebrow">PROTECTED ACCESS</p><h2>{{editing?.name??'Create user'}}</h2></div><button aria-label="Close user form" @click="userOpen=false">×</button></header><form class="editor" @submit.prevent="saveUser"><label>Name<input v-model="userForm.name" required></label><label>Email<input v-model="userForm.email" type="email" required></label><label>Role<select v-model="userForm.role"><option v-for="role in store.userRoles" :key="role" :value="role">{{role.replace('_',' ')}}</option></select></label><label class="check"><input v-model="userForm.is_active" type="checkbox"> Active account</label><p v-if="store.error" class="alert">{{store.error}}</p><button class="primary" :disabled="store.working">Save user access</button></form></section></section></template>
<style scoped>
.page{width:min(100%,54rem);margin:auto;padding:max(5.2rem,calc(env(safe-area-inset-top) + 4.4rem)) 1rem calc(6rem + env(safe-area-inset-bottom))}.page h1,.page h2,.sheet h2{font-family:Georgia,serif;color:#334736}.page h1{margin:.25rem 0}.page header>p:last-child{color:#67675f}.switch{display:grid;grid-template-columns:1fr 1fr;gap:.25rem;padding:.25rem;margin:1rem 0;border:1px solid #dcd2c2;border-radius:.8rem;background:#fffcf7}.switch button{min-height:44px;border:0;border-radius:.6rem;background:transparent;font-weight:800;color:#67675f}.switch button.active{background:#e9f2e8;color:#334736}.editor{display:grid;gap:.75rem}.editor label{display:grid;gap:.35rem;font-weight:700}.editor input,.editor textarea,.editor select{min-height:48px;border:1px solid #bfb3a2;border-radius:.7rem;background:#fff;padding:.65rem;font:inherit}.editor .check{grid-template-columns:auto 1fr;align-items:center}.editor .check input{width:24px;min-height:24px}.primary{min-height:48px;width:100%;border:0;border-radius:.75rem;background:#4f6a4e;color:#fff;font-weight:800}.read-only{margin-top:1rem;padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7}.read-only h2{margin-top:0}.read-only article{display:flex;justify-content:space-between;gap:.5rem;padding:.55rem 0;border-top:1px solid #eee5d8}.ready{color:#35633d}.review{color:#9a651e}.list{display:grid;gap:.65rem;margin-top:1rem}.card{display:grid;gap:.3rem;width:100%;padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7;text-align:left;color:#232620}.card:disabled{opacity:.75}.card p,.card small{color:#67675f}.card em{color:#7a3e14;font-size:.72rem}.top{display:flex;justify-content:space-between}.top span{padding:.2rem .55rem;border-radius:999px;background:#e9f2e8;font-size:.7rem}.pager{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.5rem;margin-top:1rem}.pager button{min-height:44px;border:1px solid #dcd2c2;border-radius:.7rem;background:#fff}.pager span{text-align:center;font-size:.75rem}.sheet{position:fixed;z-index:35;inset:0;overflow:auto;background:#f5f0e7;padding:max(1rem,env(safe-area-inset-top)) 1rem max(1rem,env(safe-area-inset-bottom))}.sheet>header,.sheet>.editor{max-width:42rem;margin:auto}.sheet>header{display:flex;justify-content:space-between}.sheet>header button{width:48px;height:48px;border:1px solid #dcd2c2;border-radius:999px;background:#fff;font-size:1.5rem}
</style>
