<script setup lang="ts">
import { onMounted } from 'vue'
import { useAdminStore } from '../stores/admin'
const emit=defineEmits<{navigate:[tab:'operations'|'staff'|'services']}>();const store=useAdminStore()
onMounted(()=>store.loadDashboard())
const money=(value:string)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(value))
const date=(value:string|null)=>value?new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Unscheduled'
</script>
<template><section class="page" aria-labelledby="admin-today-title"><header><p class="eyebrow">MANAGEMENT OVERVIEW</p><h1 id="admin-today-title">Casa Paraiso today</h1><p>Live operating, revenue, guest, and team context.</p></header><p v-if="store.error" class="alert" role="alert">{{store.error}}</p><div v-if="store.dashboard" class="metrics"><article><strong>{{store.dashboard.summary.today_appointments}}</strong><span>Appointments today</span></article><article><strong>{{money(store.dashboard.summary.today_revenue)}}</strong><span>Revenue today</span></article><article><strong>{{store.dashboard.summary.available_rewards}}</strong><span>Available rewards</span></article><article><strong>{{store.dashboard.summary.new_feedback}}</strong><span>New feedback</span></article></div><div class="actions"><button @click="emit('navigate','operations')">Run operations</button><button @click="emit('navigate','staff')">Manage team</button><button @click="emit('navigate','services')">Service catalog</button></div><section v-if="store.dashboard" aria-labelledby="upcoming-bookings-title"><div class="section-head"><div><p class="eyebrow">NEXT VISITS</p><h2 id="upcoming-bookings-title">Upcoming bookings</h2></div><span>{{store.dashboard.summary.upcoming_appointments}}</span></div><div class="agenda"><article v-for="item in store.dashboard.upcoming_appointments" :key="item.id"><strong>{{item.customer?.name??'Guest'}}</strong><span>{{item.service?.name}} · {{item.therapist?.name??'Unassigned'}}</span><small>{{date(item.starts_at)}} · {{item.appointment_number}}</small></article><p v-if="!store.dashboard.upcoming_appointments.length" class="empty">No upcoming confirmed visits.</p></div></section></section></template>
<style scoped>
.page{width:min(100%,54rem);margin:auto;padding:max(5.2rem,calc(env(safe-area-inset-top) + 4.4rem)) 1rem calc(6rem + env(safe-area-inset-bottom))}.page h1,.page h2{font-family:var(--font-display);color:var(--casa-deep-palm)}.page h1{margin:.25rem 0}.page header>p:last-child{color:var(--casa-muted)}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:.65rem;margin:1rem 0}.metrics article{display:grid;gap:.25rem;padding:1rem;border:1px solid var(--casa-border);border-radius:var(--radius-operation);background:var(--casa-paper)}.metrics strong{font:700 1.35rem var(--font-display);color:var(--casa-deep-palm)}.metrics span{font-size:.72rem;color:var(--casa-muted)}.actions{display:grid;grid-template-columns:1fr 1fr;gap:.55rem;margin:1rem 0}.actions button{min-height:48px;border:1px solid var(--casa-palm);border-radius:var(--radius-control);background:var(--casa-palm);color:white;font-weight:800}.actions button:last-child{grid-column:1/-1;background:#fff;color:var(--casa-deep-palm)}.section-head{display:flex;justify-content:space-between;align-items:end;margin-top:1.5rem}.section-head h2{margin:.15rem 0}.section-head>span{padding:.3rem .6rem;border-radius:999px;background:var(--casa-success-bg);color:var(--casa-deep-palm)}.agenda{display:grid;gap:.6rem}.agenda article{display:grid;gap:.25rem;padding:1rem;border:1px solid var(--casa-border);border-radius:var(--radius-operation);background:var(--casa-paper)}.agenda span,.agenda small{color:var(--casa-muted)}.empty{text-align:center;padding:1.5rem}
</style>
