<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useAdminStore } from '../stores/admin'
import type { AdminAddon } from '../lib/api'
const store=useAdminStore();const editing=ref<AdminAddon|null>(null);const open=ref(false);const form=reactive({name:'',description:'',duration_minutes:0,price:'',is_active:true})
onMounted(()=>store.loadAddons())
function edit(item?:AdminAddon):void{editing.value=item??null;Object.assign(form,{name:item?.name??'',description:item?.description??'',duration_minutes:item?.duration_minutes??0,price:item?.price??'',is_active:item?.is_active??true});store.clear();open.value=true}
async function save():Promise<void>{if(await store.saveAddon({...form,price:Number(form.price)},editing.value?.id))open.value=false}
</script>
<template><section class="page"><header><p class="eyebrow">OFFERING CONTROL</p><h1>Add-on catalog</h1><p>Manage shared extras, pricing, duration, and booking visibility.</p></header><div class="metrics"><article><strong>{{store.addonSummary.active}}</strong><span>Active</span></article><article><strong>{{store.addonSummary.inactive}}</strong><span>Inactive</span></article></div><p v-if="store.notice" class="notice">{{store.notice}}</p><p v-if="store.error" class="alert">{{store.error}}</p><form class="filters" @submit.prevent="store.loadAddons(1)"><input v-model="store.addonSearch" aria-label="Search add-ons" placeholder="Search add-ons"><select v-model="store.addonStatus" aria-label="Add-on status"><option value="">All states</option><option value="active">Active</option><option value="inactive">Inactive</option></select><button>Apply</button></form><button class="primary" @click="edit()">Add add-on</button><div class="list"><article v-for="item in store.addons" :key="item.id"><div class="top"><span>{{item.is_active?'Active':'Inactive'}}</span><small>{{item.duration_minutes}} min</small></div><h2>{{item.name}}</h2><strong>₱{{item.price}}</strong><p>{{item.description||'No description.'}}</p><div class="row"><button @click="edit(item)">Edit</button><button @click="store.toggleAddon(item.id)">{{item.is_active?'Deactivate':'Activate'}}</button></div></article><p v-if="!store.loading&&!store.addons.length" class="empty">No add-ons found.</p></div><div class="pager" v-if="store.addonMeta.last_page>1"><button :disabled="store.addonMeta.current_page===1" @click="store.loadAddons(store.addonMeta.current_page-1)">Previous</button><span>Page {{store.addonMeta.current_page}} of {{store.addonMeta.last_page}}</span><button :disabled="store.addonMeta.current_page===store.addonMeta.last_page" @click="store.loadAddons(store.addonMeta.current_page+1)">Next</button></div><section v-if="open" class="sheet"><header><div><p class="eyebrow">{{editing?'UPDATE':'NEW'}} ADD-ON</p><h2>{{editing?.name??'Create add-on'}}</h2></div><button aria-label="Close add-on form" @click="open=false">×</button></header><form class="editor" @submit.prevent="save"><label>Name<input v-model="form.name" required></label><label>Description<textarea v-model="form.description" rows="4"/></label><label>Duration in minutes<input v-model.number="form.duration_minutes" type="number" min="0" max="480" step="15" required></label><label>Price<input v-model="form.price" type="number" min="0" max="999999.99" step="0.01" required></label><label class="check"><input v-model="form.is_active" type="checkbox"> Available for booking</label><p v-if="store.error" class="alert">{{store.error}}</p><button class="primary" :disabled="store.working">{{store.working?'Saving…':'Save add-on'}}</button></form></section></section></template>
<style scoped>.page{width:min(100%,54rem);margin:auto;padding:max(5.2rem,calc(env(safe-area-inset-top) + 4.4rem)) 1rem calc(6rem + env(safe-area-inset-bottom))}.page h1,.page h2,.sheet h2{font-family:Georgia,serif;color:#334736}.page h1{margin:.25rem 0}.page header>p:last-child{color:#67675f}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:.6rem;margin:1rem 0}.metrics article{display:grid;padding:.8rem;border:1px solid #dcd2c2;border-radius:.8rem;background:#fffcf7}.metrics strong{font:700 1.3rem Georgia,serif}.metrics span{font-size:.72rem;color:#67675f}.filters{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;margin:1rem 0}.filters input,.filters select,.filters button,.editor input,.editor textarea{min-height:48px;border:1px solid #bfb3a2;border-radius:.7rem;background:#fff;padding:.65rem;font:inherit}.filters button{grid-column:1/-1;background:#4f6a4e;color:#fff;font-weight:800}.primary{min-height:48px;width:100%;border:0;border-radius:.75rem;background:#4f6a4e;color:#fff;font-weight:800}.list{display:grid;gap:.65rem;margin-top:1rem}.list article{padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7}.list h2{margin:.35rem 0}.list p,.list small{color:#67675f}.top,.row{display:flex;justify-content:space-between;gap:.5rem}.top span{padding:.2rem .55rem;border-radius:999px;background:#e9f2e8;font-size:.72rem}.row{margin-top:.8rem}.row button{min-height:44px;flex:1;border:1px solid #bfb3a2;border-radius:.65rem;background:#fff;font-weight:800}.pager{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.5rem;margin-top:1rem}.pager button{min-height:44px;border:1px solid #dcd2c2;border-radius:.7rem;background:#fff}.pager span{text-align:center;font-size:.75rem}.sheet{position:fixed;z-index:30;inset:0;overflow:auto;background:#f5f0e7;padding:max(1rem,env(safe-area-inset-top)) 1rem max(1rem,env(safe-area-inset-bottom))}.sheet>header,.editor{max-width:42rem;margin:auto}.sheet>header{display:flex;justify-content:space-between}.sheet>header button{width:48px;height:48px;border:1px solid #dcd2c2;border-radius:999px;background:#fff;font-size:1.5rem}.editor{display:grid;gap:.8rem}.editor label{display:grid;gap:.35rem;font-weight:700}.editor .check{grid-template-columns:auto 1fr;align-items:center}.editor .check input{width:24px;min-height:24px}.empty{text-align:center;padding:1.5rem}</style>
