<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{useAdminStore}from'../stores/admin';
const store=useAdminStore();const week=ref(sunday(new Date()));const shift=reactive({staff_profile_id:0,schedule_date:'',start_time:'13:00',end_time:'18:00',ends_next_day:false})
const grouped=computed(()=>{const rows=store.roster?.draft_shifts??[];return rows.reduce<Record<string,typeof rows>>((result,item)=>{(result[item.schedule_date]??=[]).push(item);return result},{})})
onMounted(()=>store.loadRoster(week.value));function sunday(value:Date):string{const day=new Date(value);day.setDate(day.getDate()-day.getDay());return day.toISOString().slice(0,10)}
async function changeWeek(offset:number):Promise<void>{const value=new Date(`${week.value}T12:00:00`);value.setDate(value.getDate()+offset*7);week.value=sunday(value);await store.loadRoster(week.value)}
async function add():Promise<void>{if(!shift.staff_profile_id)shift.staff_profile_id=store.roster?.resources[0]?.id??0;if(!shift.schedule_date)shift.schedule_date=store.roster?.week_start??'';await store.addRosterShift({...shift})}
const person=(id:number)=>store.roster?.resources.find(item=>item.id===id)?.name??'Therapist'
</script>
<template><section class="page"><header><p class="eyebrow">DATED TEAM COVERAGE</p><h1>Weekly roster</h1><p>Copy, adjust, and publish the therapist shifts that drive mobile booking availability.</p></header><p v-if="store.notice" class="notice">{{store.notice}}</p><p v-if="store.error" class="alert">{{store.error}}</p><div class="week"><button @click="changeWeek(-1)">Previous</button><strong>{{store.roster?.week_start}}–{{store.roster?.week_end}}</strong><button @click="changeWeek(1)">Next</button></div><div v-if="store.roster" class="status"><span>{{store.roster.published_at?'Published':'Not published'}}</span><small>{{store.roster.has_draft?'Draft changes ready':'No draft shifts'}}</small></div><div class="actions"><button :disabled="store.working" @click="store.copyRoster">Copy previous week</button><button :disabled="store.working||!store.roster?.has_draft" @click="store.publishRoster">Publish roster</button></div><form v-if="store.roster" class="editor" @submit.prevent="add"><label>Therapist<select v-model.number="shift.staff_profile_id" required><option v-for="resource in store.roster.resources" :key="resource.id" :value="resource.id">{{resource.name}}</option></select></label><label>Date<input v-model="shift.schedule_date" type="date" :min="store.roster.week_start" :max="store.roster.week_end" required></label><label>Start<input v-model="shift.start_time" type="time" min="13:00" step="1800" required></label><label>End<input v-model="shift.end_time" type="time" step="1800" required></label><label class="check"><input v-model="shift.ends_next_day" type="checkbox"> Ends at midnight</label><button :disabled="store.working">Add draft shift</button></form><section v-if="store.roster" class="days"><article v-for="(items,date) in grouped" :key="date"><h2>{{date}}</h2><div v-for="item in items" :key="item.id" class="shift"><span><strong>{{person(item.staff_profile_id)}}</strong><small>{{item.start_time}}–{{item.ends_next_day?'12:00 midnight':item.end_time}}</small></span><button @click="store.removeRosterShift(item.id)">Remove</button></div></article><p v-if="!store.roster.draft_shifts.length" class="empty">Copy the previous roster or add a draft shift.</p></section></section></template>
<style scoped>.page{width:min(100%,54rem);margin:auto;padding:max(8.2rem,calc(env(safe-area-inset-top) + 7.5rem)) 1rem calc(6rem + env(safe-area-inset-bottom))}.page h1,.page h2{font-family:Georgia,serif;color:#334736}.page h1{margin:.25rem 0}.page header>p:last-child{color:#67675f}.week{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.5rem;margin:1rem 0}.week button,.actions button,.shift button{min-height:44px;border:1px solid #bfb3a2;border-radius:.65rem;background:#fff;font-weight:800}.week strong{text-align:center;font-size:.72rem}.status{display:flex;justify-content:space-between;padding:.8rem;border:1px solid #dcd2c2;border-radius:.8rem;background:#fffcf7}.actions{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;margin:1rem 0}.actions button:last-child{background:#4f6a4e;color:white}.editor{display:grid;grid-template-columns:1fr 1fr;gap:.6rem;padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7}.editor label{display:grid;gap:.3rem;font-weight:700}.editor input,.editor select{min-height:48px;border:1px solid #bfb3a2;border-radius:.7rem;background:#fff;padding:.6rem;font:inherit}.editor .check{grid-template-columns:auto 1fr;align-items:center}.editor .check input{width:24px;min-height:24px}.editor>button{grid-column:1/-1;min-height:48px;border:0;border-radius:.7rem;background:#4f6a4e;color:white;font-weight:800}.days{display:grid;gap:.7rem;margin-top:1rem}.days article{padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7}.days h2{margin:0 0 .5rem}.shift{display:flex;justify-content:space-between;align-items:center;gap:.5rem;padding:.5rem 0;border-top:1px solid #eee5d8}.shift span{display:grid}.shift small{color:#67675f}.empty{text-align:center;padding:1.5rem}</style>
