<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { appointmentStatusLabel, formatAppointmentDate, formatPeso } from '../lib/appointments'
import { manilaDateTimeInput, manilaInputToIso } from '../lib/reception'
import type { OperationalAppointment } from '../lib/api'
import { useReceptionStore } from '../stores/reception'
import MobileConfirmDialog from '../components/MobileConfirmDialog.vue'
import MobileFilterDisclosure from '../components/MobileFilterDisclosure.vue'

const store = useReceptionStore()
const formOpen = ref(false); const editingId = ref<number | undefined>(); const finishTarget = ref<OperationalAppointment | null>(null)
const outcomeTarget = ref<{ item: OperationalAppointment; status: 'cancelled' | 'no_show' } | null>(null)
const form = reactive({ customerId: 0, serviceId: 0, therapistId: 0, startsAt: '', addonCodes: [] as string[], customerNotes: '', internalNotes: '' })
const payment = reactive({ amount: '', status: 'paid', method: '', paidAt: '', notes: '' })
onMounted(async () => { await Promise.all([store.loadAppointments(), store.loadAppointmentOptions()]) })

function openNew(): void { const options=store.appointmentOptions; if(!options)return; editingId.value=undefined; form.customerId=options.customers[0]?.id??0; form.serviceId=options.services[0]?.id??0; form.therapistId=0; form.startsAt=manilaDateTimeInput(options.initial_start_at); form.addonCodes=[]; form.customerNotes=''; form.internalNotes=''; store.availableTherapists=[]; formOpen.value=true }
function openEdit(item:OperationalAppointment):void { editingId.value=item.id; form.customerId=item.customer?.id??0; form.serviceId=item.service?.id??0; form.therapistId=item.therapist?.id??0; form.startsAt=manilaDateTimeInput(item.starts_at); form.addonCodes=item.addons.map(a=>a.code); form.customerNotes=item.customer_notes??''; form.internalNotes=item.internal_notes??''; store.availableTherapists=item.therapist?[item.therapist]:[]; formOpen.value=true }
async function findTherapists():Promise<void>{ if(form.serviceId&&form.startsAt) await store.findTherapists(form.serviceId,manilaInputToIso(form.startsAt),form.addonCodes,editingId.value) }
async function save():Promise<void>{ const ok=await store.saveAppointment({customer_profile_id:form.customerId,service_id:form.serviceId,staff_profile_id:form.therapistId,preferred_staff_profile_id:null,scheduled_start_at:manilaInputToIso(form.startsAt),status:'confirmed',addon_codes:form.addonCodes,customer_notes:form.customerNotes||null,internal_notes:form.internalNotes||null},editingId.value); if(ok)formOpen.value=false }
function outcome(item:OperationalAppointment,status:'cancelled'|'no_show'):void{outcomeTarget.value={item,status}}
async function confirmOutcome(reason?:string):Promise<void>{if(!outcomeTarget.value)return;const target=outcomeTarget.value;outcomeTarget.value=null;await store.outcome(target.item,target.status,reason||undefined)}
async function clearFilters():Promise<void>{store.appointmentSearch='';store.appointmentDate='';store.appointmentStatus='';await store.loadAppointments(1)}
function openFinish(item:OperationalAppointment):void { const o=store.appointmentOptions; finishTarget.value=item; payment.amount=item.expected_amount; payment.status='paid'; payment.method=o?.default_payment_method??'Cash'; payment.paidAt=manilaDateTimeInput(new Date().toISOString()); payment.notes='' }
async function finish():Promise<void>{ if(!finishTarget.value)return; const received=['partial','paid'].includes(payment.status); const ok=await store.complete(finishTarget.value,{amount:payment.amount,payment_status:payment.status,payment_method:received?payment.method:null,paid_at:received?manilaInputToIso(payment.paidAt):null,notes:payment.notes||null}); if(ok)finishTarget.value=null }
</script>

<template>
  <section class="ops-page" aria-labelledby="bookings-title"><header class="heading"><div><p class="eyebrow">Front desk schedule</p><h1 id="bookings-title">Bookings</h1></div><button class="primary" @click="openNew">New booking</button></header>
    <div class="summary"><span><b>{{store.appointmentSummary.confirmed}}</b> Confirmed</span><span><b>{{store.appointmentSummary.completed}}</b> Completed</span><span><b>{{store.appointmentSummary.cancelled}}</b> Cancelled</span></div>
    <MobileFilterDisclosure :active-count="Number(!!store.appointmentSearch)+Number(!!store.appointmentDate)+Number(!!store.appointmentStatus)" @clear="clearFilters"><form class="filters" @submit.prevent="store.loadAppointments(1)"><label>Search<input v-model="store.appointmentSearch" placeholder="Booking or customer"></label><label>Date<input v-model="store.appointmentDate" type="date"></label><label>Status<select v-model="store.appointmentStatus"><option value="">All statuses</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No-show</option></select></label><button>Apply filters</button></form></MobileFilterDisclosure>
    <p v-if="store.error" class="alert" role="alert">{{Object.values(store.fields).flat()[0]??store.error}}</p><p v-if="store.notice" class="notice" role="status">{{store.notice}}</p><div v-if="store.loading" class="loading">Loading bookings…</div>
    <div v-else class="ops-list"><article v-for="item in store.appointments" :key="item.id" class="ops-card"><div class="card-top"><small :data-status="item.status">{{appointmentStatusLabel(item.status)}}</small><b>{{formatAppointmentDate(item.starts_at)}}</b></div><h2>{{item.customer?.name}}</h2><p>{{item.service?.name}} · {{item.therapist?.name??'Unassigned'}}</p><p>{{item.appointment_number}} · {{formatPeso(item.expected_amount)}}</p><div class="actions"><button v-if="item.actions.can_edit" @click="openEdit(item)">Edit</button><button v-if="item.actions.can_finish" class="success" @click="openFinish(item)">Finish & pay</button><button v-if="item.actions.can_mark_no_show" @click="outcome(item,'no_show')">No-show</button><button v-if="item.actions.can_cancel" class="danger" @click="outcome(item,'cancelled')">Cancel</button></div></article></div>
    <nav v-if="store.appointmentMeta.last_page>1" class="pager"><button :disabled="store.appointmentMeta.current_page<=1" @click="store.loadAppointments(store.appointmentMeta.current_page-1)">Previous</button><span>Page {{store.appointmentMeta.current_page}} of {{store.appointmentMeta.last_page}}</span><button :disabled="store.appointmentMeta.current_page>=store.appointmentMeta.last_page" @click="store.loadAppointments(store.appointmentMeta.current_page+1)">Next</button></nav>

    <section v-if="formOpen&&store.appointmentOptions" v-mobile-modal="() => formOpen=false" class="sheet" role="dialog" aria-modal="true" aria-labelledby="booking-form-title"><header><h2 id="booking-form-title">{{editingId?'Edit booking':'New booking'}}</h2><button aria-label="Close booking form" @click="formOpen=false">×</button></header><form @submit.prevent="save"><label>Customer<select v-model.number="form.customerId" required><option v-for="c in store.appointmentOptions.customers" :key="c.id" :value="c.id">{{c.customer_code}} · {{c.name}}</option></select></label><label>Service<select v-model.number="form.serviceId" required @change="form.therapistId=0;store.availableTherapists=[]"><option v-for="s in store.appointmentOptions.services" :key="s.id" :value="s.id">{{s.name}} · {{formatPeso(s.price)}}</option></select></label><fieldset><legend>Paid add-ons</legend><label v-for="a in store.appointmentOptions.addons" :key="a.code" class="check"><input v-model="form.addonCodes" type="checkbox" :value="a.code"><span>{{a.name}} · {{formatPeso(a.price)}}</span></label></fieldset><label>Start time<input v-model="form.startsAt" type="datetime-local" required step="1800"></label><button type="button" class="secondary" :disabled="store.working" @click="findTherapists">{{store.working?'Checking…':'Find available therapists'}}</button><label>Therapist<select v-model.number="form.therapistId" required><option :value="0" disabled>Select therapist</option><option v-for="t in store.availableTherapists" :key="t.id" :value="t.id">{{t.name}}</option></select></label><label>Customer note<textarea v-model="form.customerNotes" rows="3"></textarea></label><label>Internal note<textarea v-model="form.internalNotes" rows="3"></textarea></label><p v-if="store.error" class="alert">{{Object.values(store.fields).flat()[0]??store.error}}</p><button class="primary" :disabled="store.working||!form.therapistId">{{store.working?'Saving…':editingId?'Save changes':'Confirm booking'}}</button></form></section>
    <section v-if="finishTarget&&store.appointmentOptions" v-mobile-modal="() => finishTarget=null" class="sheet" role="dialog" aria-modal="true" aria-labelledby="finish-title"><header><h2 id="finish-title">Finish {{finishTarget.appointment_number}}</h2><button aria-label="Close finish form" @click="finishTarget=null">×</button></header><form @submit.prevent="finish"><label>Amount<input v-model="payment.amount" type="number" min="0" max="999999.99" step="0.01" required></label><label>Payment status<select v-model="payment.status"><option value="unpaid">Unpaid</option><option value="partial">Partially paid</option><option value="paid">Paid</option></select></label><label v-if="payment.status!=='unpaid'">Method<select v-model="payment.method"><option v-for="m in store.appointmentOptions.payment_methods" :key="m">{{m}}</option></select></label><label v-if="payment.status!=='unpaid'">Paid at<input v-model="payment.paidAt" type="datetime-local" required></label><label>Notes<textarea v-model="payment.notes" rows="3"></textarea></label><p v-if="store.error" class="alert">{{Object.values(store.fields).flat()[0]??store.error}}</p><button class="primary" :disabled="store.working">{{store.working?'Finishing…':'Finish service'}}</button></form></section>
    <MobileConfirmDialog :open="!!outcomeTarget" :title="outcomeTarget?.status==='cancelled'?'Cancel booking?':'Mark as no-show?'" :message="outcomeTarget ? `${outcomeTarget.status==='cancelled'?'Cancel':'Mark no-show for'} ${outcomeTarget.item.appointment_number}?` : ''" :confirm-label="outcomeTarget?.status==='cancelled'?'Cancel booking':'Mark no-show'" prompt-label="Reason (optional)" destructive @cancel="outcomeTarget=null" @confirm="confirmOutcome" />
  </section>
</template>

<style scoped>
.ops-page{width:min(100%,54rem);margin:auto;padding:max(1.25rem,env(safe-area-inset-top)) 1rem calc(6rem + env(safe-area-inset-bottom))}.heading,.card-top,.sheet>header{display:flex;justify-content:space-between;align-items:center;gap:1rem}.ops-page h1,.ops-page h2,.sheet h2{font-family:Georgia,serif;color:#334736}.heading .primary{min-height:48px}.summary{display:grid;grid-template-columns:repeat(3,1fr);margin:1rem 0;border:1px solid #dcd2c2;border-radius:1rem;overflow:hidden;background:#fffcf7}.summary span{display:grid;padding:.7rem .3rem;text-align:center;font-size:.7rem}.summary span+span{border-left:1px solid #dcd2c2}.summary b{font-size:1.15rem;color:#334736}.filters{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;margin-bottom:1rem}.filters input,.filters select,.filters button,.sheet input,.sheet select,.sheet textarea{width:100%;min-height:48px;border:1px solid #bfb3a2;border-radius:.7rem;background:#fff;padding:.65rem;font:inherit}.filters button{background:#4f6a4e;color:#fff;font-weight:800}.notice{padding:.75rem;border-radius:.75rem;background:#e9f2e8;color:#334736}.loading{text-align:center;padding:2rem}.ops-list{display:grid;gap:.75rem}.ops-card{padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7}.ops-card h2{margin:.6rem 0 .2rem;font-size:1.2rem}.ops-card p{margin:.25rem 0;color:#67675f}.card-top small{padding:.2rem .5rem;border-radius:999px;background:#e9f2e8;color:#334736}.actions{display:grid;grid-template-columns:repeat(2,1fr);gap:.5rem;margin-top:.8rem}.actions button,.pager button,.secondary{min-height:44px;border:1px solid #dcd2c2;border-radius:.7rem;background:#fff;color:#334736;font-weight:800}.actions .success{background:#e9f2e8;border-color:#4f6a4e}.actions .danger{background:#fff7f5;color:#8c2f26}.pager{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.5rem;margin-top:1rem}.pager span{text-align:center;font-size:.8rem}.sheet{position:fixed;z-index:30;inset:0;overflow:auto;background:#f5f0e7;padding:max(1rem,env(safe-area-inset-top)) 1rem max(1rem,env(safe-area-inset-bottom))}.sheet>header,.sheet>form{max-width:40rem;margin:auto}.sheet>header{margin-bottom:1rem}.sheet>header button{width:48px;height:48px;border:1px solid #dcd2c2;border-radius:999px;background:#fff;font-size:1.5rem}.sheet>form{display:grid;gap:1rem;padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7}.sheet label{font-weight:700}.sheet fieldset{border:1px solid #dcd2c2;border-radius:.75rem}.sheet .check{min-height:44px;display:flex;align-items:center;gap:.5rem;font-weight:500}.sheet .check input{width:22px;min-height:22px}.sheet .primary,.sheet .secondary{min-height:48px}.sheet .primary{border:0;border-radius:.7rem;background:#4f6a4e;color:#fff;font-weight:800}
</style>
