<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { formatAppointmentDate, formatPeso } from '../lib/appointments'
import { manilaDateTimeInput, manilaInputToIso, paymentStatusLabel } from '../lib/reception'
import type { OperationalTransaction } from '../lib/api'
import { useReceptionStore } from '../stores/reception'
import MobileSkeleton from '../components/MobileSkeleton.vue'
import { useInitialLoad } from '../composables/useInitialLoad'

const store=useReceptionStore();const formOpen=ref(false);const editingId=ref<number|undefined>();const form=reactive({appointmentId:0,customerId:0,serviceId:0,amount:'',status:'paid',method:'',paidAt:'',notes:''})
const { initialLoading, loadInitial } = useInitialLoad()
onMounted(()=>void loadInitial(async()=>{await Promise.all([store.loadTransactions(),store.loadTransactionOptions()])}))
function reset():void{const o=store.transactionOptions;if(!o)return;editingId.value=undefined;form.appointmentId=0;form.customerId=o.customers[0]?.id??0;form.serviceId=o.services[0]?.id??0;form.amount='';form.status='paid';form.method=o.default_payment_method;form.paidAt=manilaDateTimeInput(new Date().toISOString());form.notes='';formOpen.value=true}
function edit(t:OperationalTransaction):void{editingId.value=t.id;form.appointmentId=t.appointment?.id??0;form.customerId=t.customer?.id??0;form.serviceId=t.service?.id??0;form.amount=t.amount;form.status=t.payment_status;form.method=t.payment_method??store.transactionOptions?.default_payment_method??'Cash';form.paidAt=manilaDateTimeInput(t.paid_at);form.notes=t.notes??'';formOpen.value=true}
function appointmentChanged():void{const a=store.transactionOptions?.appointments.find(a=>a.id===form.appointmentId);if(a){form.customerId=a.customer_profile_id;form.serviceId=a.service_id;form.amount=a.expected_amount}}
async function save():Promise<void>{const received=['partial','paid','refunded'].includes(form.status);const ok=await store.saveTransaction({customer_profile_id:form.customerId||null,appointment_id:form.appointmentId||null,service_id:form.serviceId||null,amount:form.amount,payment_status:form.status,payment_method:received?form.method:null,paid_at:received?manilaInputToIso(form.paidAt):null,notes:form.notes||null},editingId.value);if(ok)formOpen.value=false}
</script>
<template>
  <section class="ops-page" aria-labelledby="payments-title"><header class="heading"><div><p class="eyebrow">Manual records</p><h1 id="payments-title">Payments</h1></div><button class="primary" @click="reset">Record payment</button></header><div class="summary"><span><b>{{formatPeso(store.transactionSummary.paid)}}</b> Paid total</span><span><b>{{store.transactionSummary.unpaid_count}}</b> Unpaid</span><span><b>{{store.transactionSummary.partial_count}}</b> Partial</span></div><form class="filters" @submit.prevent="store.loadTransactions(1)"><input v-model="store.transactionSearch" placeholder="Number, customer, service" aria-label="Search payments"><select v-model="store.transactionStatus" aria-label="Payment status"><option value="">All statuses</option><option v-for="s in store.transactionOptions?.payment_statuses??[]" :key="s" :value="s">{{paymentStatusLabel(s)}}</option></select><button>Apply</button></form><p v-if="store.error" class="alert">{{Object.values(store.fields).flat()[0]??store.error}}</p><p v-if="store.notice" class="notice">{{store.notice}}</p><MobileSkeleton v-if="initialLoading" variant="list" label="Loading payments" /><div v-else class="list"><button v-for="t in store.transactions" :key="t.id" class="card" @click="edit(t)"><div><strong>{{formatPeso(t.amount)}}</strong><small :data-status="t.payment_status">{{paymentStatusLabel(t.payment_status)}}</small></div><span>{{t.customer?.name}} · {{t.service?.name??'Service not selected'}}</span><small>{{t.transaction_number}} · {{formatAppointmentDate(t.paid_at)}}</small></button></div><nav v-if="store.transactionMeta.last_page>1" class="pager"><button :disabled="store.transactionMeta.current_page<=1" @click="store.loadTransactions(store.transactionMeta.current_page-1)">Previous</button><span>Page {{store.transactionMeta.current_page}} of {{store.transactionMeta.last_page}}</span><button :disabled="store.transactionMeta.current_page>=store.transactionMeta.last_page" @click="store.loadTransactions(store.transactionMeta.current_page+1)">Next</button></nav>
    <section v-if="formOpen&&store.transactionOptions" class="sheet" role="dialog" aria-modal="true" aria-labelledby="payment-form-title"><header><h2 id="payment-form-title">{{editingId?'Edit payment':'Record payment'}}</h2><button aria-label="Close payment form" @click="formOpen=false">×</button></header><form @submit.prevent="save"><label>Appointment (optional)<select v-model.number="form.appointmentId" @change="appointmentChanged"><option :value="0">No linked appointment</option><option v-for="a in store.transactionOptions.appointments" :key="a.id" :value="a.id">{{a.appointment_number}} · {{a.customer_name}} · {{a.service_name}}</option></select></label><label>Customer<select v-model.number="form.customerId" required :disabled="!!form.appointmentId"><option v-for="c in store.transactionOptions.customers" :key="c.id" :value="c.id">{{c.customer_code}} · {{c.name}}</option></select></label><label>Service<select v-model.number="form.serviceId" :disabled="!!form.appointmentId"><option :value="0">No service</option><option v-for="s in store.transactionOptions.services" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label>Amount<input v-model="form.amount" type="number" min="0" max="999999.99" step="0.01" required></label><label>Status<select v-model="form.status"><option v-for="s in store.transactionOptions.payment_statuses" :key="s" :value="s">{{paymentStatusLabel(s)}}</option></select></label><label v-if="['partial','paid','refunded'].includes(form.status)">Method<select v-model="form.method"><option v-for="m in store.transactionOptions.payment_methods" :key="m">{{m}}</option></select></label><label v-if="['partial','paid','refunded'].includes(form.status)">Paid at<input v-model="form.paidAt" type="datetime-local" required></label><label>Notes<textarea v-model="form.notes" rows="3"></textarea></label><p v-if="store.error" class="alert">{{Object.values(store.fields).flat()[0]??store.error}}</p><button class="primary" :disabled="store.working">{{store.working?'Saving…':'Save payment'}}</button></form></section>
  </section>
</template>
<style scoped>
.ops-page{width:min(100%,54rem);margin:auto;padding:max(1.25rem,env(safe-area-inset-top)) 1rem calc(6rem + env(safe-area-inset-bottom))}.heading,.sheet>header,.card>div{display:flex;justify-content:space-between;align-items:center;gap:1rem}.ops-page h1,.sheet h2{font-family:Georgia,serif;color:#334736}.heading .primary{min-height:48px}.summary{display:grid;grid-template-columns:repeat(3,1fr);margin:1rem 0;border:1px solid #dcd2c2;border-radius:1rem;overflow:hidden;background:#fffcf7}.summary span{display:grid;padding:.7rem .3rem;text-align:center;font-size:.7rem}.summary span+span{border-left:1px solid #dcd2c2}.summary b{font-size:1rem;color:#334736}.filters{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;margin-bottom:1rem}.filters input,.filters select,.filters button,.sheet input,.sheet select,.sheet textarea{width:100%;min-height:48px;border:1px solid #bfb3a2;border-radius:.7rem;background:#fff;padding:.65rem;font:inherit}.filters button{grid-column:1/-1;background:#4f6a4e;color:#fff;font-weight:800}.notice{padding:.75rem;background:#e9f2e8;color:#334736;border-radius:.75rem}.loading{text-align:center;padding:2rem}.list{display:grid;gap:.65rem}.card{display:grid;gap:.35rem;width:100%;padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7;color:#232620;text-align:left}.card>div small{padding:.2rem .5rem;border-radius:999px;background:#e9f2e8;color:#334736}.card>span,.card>small{color:#67675f}.pager{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.5rem;margin-top:1rem}.pager button{min-height:44px;border:1px solid #dcd2c2;border-radius:.7rem;background:#fff}.pager span{text-align:center;font-size:.8rem}.sheet{position:fixed;z-index:30;inset:0;overflow:auto;background:#f5f0e7;padding:max(1rem,env(safe-area-inset-top)) 1rem max(1rem,env(safe-area-inset-bottom))}.sheet>header,.sheet>form{max-width:40rem;margin:auto}.sheet>header{margin-bottom:1rem}.sheet>header button{width:48px;height:48px;border:1px solid #dcd2c2;border-radius:999px;background:#fff;font-size:1.5rem}.sheet>form{display:grid;gap:1rem;padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7}.sheet label{font-weight:700}.sheet .primary{min-height:48px;border:0;border-radius:.7rem;background:#4f6a4e;color:#fff;font-weight:800}
</style>
