<script setup lang="ts">
import { onMounted, reactive, watch } from 'vue'
import { formatAppointmentDate, formatPeso } from '../lib/appointments'
import { paymentStatusLabel } from '../lib/reception'
import { useReceptionStore } from '../stores/reception'
import MobileSkeleton from '../components/MobileSkeleton.vue'
import { useInitialLoad } from '../composables/useInitialLoad'

const store=useReceptionStore(); const form=reactive({phone:'',address:'',contact_preference:'',notes:''})
const { initialLoading, loadInitial } = useInitialLoad(() => store.hasCustomers())
watch(()=>store.selectedCustomer,(value)=>{if(value){form.phone=value.phone??'';form.address=value.address??'';form.contact_preference=value.contact_preference??'';form.notes=value.notes??''}},{immediate:true})
onMounted(()=>void loadInitial(()=>store.loadCustomers()))
async function save():Promise<void>{if(!store.selectedCustomer)return;await store.saveCustomer(store.selectedCustomer.id,{phone:form.phone||null,address:form.address||null,contact_preference:form.contact_preference||null,notes:form.notes||null})}
</script>
<template>
  <section class="ops-page" aria-labelledby="customers-title"><header><p class="eyebrow">Customer records</p><h1 id="customers-title">Customers</h1><p>Find contact details and visit history without changing account identity.</p></header><form class="search" @submit.prevent="store.loadCustomers(1)"><input v-model="store.customerSearch" placeholder="Name, code, or phone" aria-label="Search customers"><button>Search</button></form>
    <p v-if="store.error" class="alert">{{Object.values(store.fields).flat()[0]??store.error}}</p><p v-if="store.notice" class="notice">{{store.notice}}</p><MobileSkeleton v-if="initialLoading" variant="list" label="Loading customers" /><div v-else class="list"><button v-for="customer in store.customers" :key="customer.id" class="card" @click="store.openCustomer(customer.id)"><strong>{{customer.name}}</strong><span>{{customer.customer_code}} · {{customer.phone??'No phone'}}</span><small>{{customer.appointments_count}} visits · {{customer.transactions_count}} payments</small></button></div>
    <nav v-if="store.customerMeta.last_page>1" class="pager"><button :disabled="store.customerMeta.current_page<=1" @click="store.loadCustomers(store.customerMeta.current_page-1)">Previous</button><span>Page {{store.customerMeta.current_page}} of {{store.customerMeta.last_page}}</span><button :disabled="store.customerMeta.current_page>=store.customerMeta.last_page" @click="store.loadCustomers(store.customerMeta.current_page+1)">Next</button></nav>
    <section v-if="store.selectedCustomer" class="sheet" role="dialog" aria-modal="true" aria-labelledby="customer-detail-title"><header><div><p class="eyebrow">{{store.selectedCustomer.customer_code}}</p><h2 id="customer-detail-title">{{store.selectedCustomer.name}}</h2></div><button aria-label="Close customer detail" @click="store.selectedCustomer=null">×</button></header><div class="detail"><section><h3>Contact</h3><p>{{store.selectedCustomer.email}}</p><form @submit.prevent="save"><label>Phone<input v-model="form.phone"></label><label>Address<textarea v-model="form.address" rows="3"></textarea></label><label>Preferred contact<select v-model="form.contact_preference"><option value="">No preference</option><option v-for="o in store.selectedCustomer.contact_preferences" :key="o.value" :value="o.value">{{o.label}}</option></select></label><label>Operational notes<textarea v-model="form.notes" rows="4"></textarea></label><p v-if="store.error" class="alert">{{Object.values(store.fields).flat()[0]??store.error}}</p><button class="primary" :disabled="store.working">{{store.working?'Saving…':'Save contact details'}}</button></form></section><section><h3>Recent visits</h3><article v-for="a in store.selectedCustomer.appointments" :key="a.id" class="history"><strong>{{a.service}}</strong><span>{{formatAppointmentDate(a.starts_at)}} · {{a.status.replace('_',' ')}}</span><small>{{a.appointment_number}} · {{a.therapist}}</small></article><p v-if="!store.selectedCustomer.appointments.length">No visits.</p></section><section><h3>Recent payments</h3><article v-for="t in store.selectedCustomer.transactions" :key="t.id" class="history"><strong>{{formatPeso(t.amount)}} · {{paymentStatusLabel(t.payment_status)}}</strong><span>{{t.service}} · {{formatAppointmentDate(t.paid_at)}}</span><small>{{t.transaction_number}}</small></article><p v-if="!store.selectedCustomer.transactions.length">No payments.</p></section><section><h3>Feedback</h3><article v-for="f in store.selectedCustomer.feedback" :key="f.id" class="history"><strong>{{'★'.repeat(f.rating)}} · {{f.service}}</strong><span>{{f.comment??'No written comment.'}}</span></article><p v-if="!store.selectedCustomer.feedback.length">No feedback.</p></section></div></section>
  </section>
</template>
<style scoped>
.ops-page{width:min(100%,54rem);margin:auto;padding:max(1.25rem,env(safe-area-inset-top)) 1rem calc(6rem + env(safe-area-inset-bottom))}.ops-page h1,.sheet h2,.sheet h3{font-family:Georgia,serif;color:#334736}.ops-page header p{margin:.25rem 0}.search{display:grid;grid-template-columns:1fr auto;gap:.5rem;margin:1rem 0}.search input,.search button,.sheet input,.sheet textarea,.sheet select{min-height:48px;border:1px solid #bfb3a2;border-radius:.7rem;background:#fff;padding:.65rem;font:inherit}.search button{background:#4f6a4e;color:#fff;font-weight:800}.notice{padding:.75rem;background:#e9f2e8;color:#334736;border-radius:.75rem}.loading{text-align:center;padding:2rem}.list{display:grid;gap:.65rem}.card{min-height:84px;display:grid;gap:.25rem;width:100%;padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7;color:#232620;text-align:left}.card span,.card small{color:#67675f}.pager{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.5rem;margin-top:1rem}.pager button{min-height:44px;border:1px solid #dcd2c2;border-radius:.7rem;background:#fff}.pager span{text-align:center;font-size:.8rem}.sheet{position:fixed;z-index:30;inset:0;overflow:auto;background:#f5f0e7;padding:max(1rem,env(safe-area-inset-top)) 1rem max(1rem,env(safe-area-inset-bottom))}.sheet>header,.detail{max-width:42rem;margin:auto}.sheet>header{display:flex;justify-content:space-between;align-items:flex-start}.sheet>header button{width:48px;height:48px;border:1px solid #dcd2c2;border-radius:999px;background:#fff;font-size:1.5rem}.detail{display:grid;gap:1rem}.detail>section{padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7}.detail form{display:grid;gap:.8rem}.detail label{font-weight:700}.detail input,.detail textarea,.detail select{width:100%}.primary{min-height:48px;border:0;border-radius:.7rem;background:#4f6a4e;color:#fff;font-weight:800}.history{display:grid;gap:.2rem;padding:.75rem 0;border-top:1px solid #eee5d8}.history span,.history small{color:#67675f}
</style>
