<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { appointmentStatusLabel, formatAppointmentDate, formatPeso } from '../lib/appointments'
import { manilaDateTimeInput, manilaInputToIso } from '../lib/reception'
import type { OperationalAppointment } from '../lib/api'
import { useStaffStore } from '../stores/staff'
import MobileConfirmDialog from '../components/MobileConfirmDialog.vue'
import MobileFilterDisclosure from '../components/MobileFilterDisclosure.vue'
import MobileSkeleton from '../components/MobileSkeleton.vue'
import { useInitialLoad } from '../composables/useInitialLoad'

const store=useStaffStore();const finishTarget=ref<OperationalAppointment|null>(null);const noShowTarget=ref<OperationalAppointment|null>(null)
const payment=reactive({amount:'',status:'paid',method:'Cash',paidAt:'',notes:''})
const { initialLoading, loadInitial } = useInitialLoad()
onMounted(()=>void loadInitial(()=>store.loadAppointments()))
function noShow(item:OperationalAppointment):void{noShowTarget.value=item}
async function confirmNoShow(reason?:string):Promise<void>{if(!noShowTarget.value)return;const item=noShowTarget.value;noShowTarget.value=null;await store.noShow(item,reason||undefined)}
async function clearFilters():Promise<void>{store.appointmentSearch='';store.appointmentDate='';store.appointmentStatus='';await store.loadAppointments(1)}
function openFinish(item:OperationalAppointment):void{finishTarget.value=item;payment.amount=item.expected_amount;payment.status='paid';payment.method='Cash';payment.paidAt=manilaDateTimeInput(new Date().toISOString());payment.notes=''}
async function finish():Promise<void>{if(!finishTarget.value)return;const received=['partial','paid'].includes(payment.status);const ok=await store.complete(finishTarget.value,{amount:payment.amount,payment_status:payment.status,payment_method:received?payment.method:null,paid_at:received?manilaInputToIso(payment.paidAt):null,notes:payment.notes||null});if(ok)finishTarget.value=null}
</script>

<template>
  <section class="page" aria-labelledby="my-schedule-title"><header><p class="eyebrow">Assigned treatments</p><h1 id="my-schedule-title">My schedule</h1><p>Review guest notes, finish treatments, and record no-shows.</p></header>
    <div class="summary"><span><b>{{store.appointmentSummary.confirmed}}</b> Confirmed</span><span><b>{{store.appointmentSummary.completed}}</b> Completed</span><span><b>{{store.appointmentSummary.no_show}}</b> No-show</span></div>
    <MobileFilterDisclosure :active-count="Number(!!store.appointmentSearch)+Number(!!store.appointmentDate)+Number(!!store.appointmentStatus)" @clear="clearFilters"><form class="filters" @submit.prevent="store.loadAppointments(1)"><label>Search<input v-model="store.appointmentSearch" placeholder="Booking or guest"></label><label>Date<input v-model="store.appointmentDate" type="date"></label><label>Status<select v-model="store.appointmentStatus"><option value="">All statuses</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No-show</option></select></label><button>Apply filters</button></form></MobileFilterDisclosure>
    <p v-if="store.error" class="alert" role="alert">{{Object.values(store.fields).flat()[0]??store.error}}</p><p v-if="store.notice" class="notice" role="status">{{store.notice}}</p><MobileSkeleton v-if="initialLoading" variant="list" label="Loading your schedule" />
    <div v-else class="list"><article v-for="item in store.appointments" :key="item.id" class="card"><div class="top"><small>{{appointmentStatusLabel(item.status)}}</small><b>{{formatAppointmentDate(item.starts_at)}}</b></div><h2>{{item.customer?.name}}</h2><p>{{item.service?.name}} · {{formatPeso(item.expected_amount)}}</p><p v-if="item.customer_notes"><b>Guest note:</b> {{item.customer_notes}}</p><p v-if="item.addons.length">Add-ons: {{item.addons.map(a=>a.name).join(', ')}}</p><div class="actions"><button v-if="item.actions.can_finish" class="success" @click="openFinish(item)">Finish & record payment</button><button v-if="item.actions.can_mark_no_show" @click="noShow(item)">Mark no-show</button></div></article><div v-if="!store.appointments.length" class="empty">No treatments match these filters.</div></div>
    <nav v-if="store.appointmentMeta.last_page>1" class="pager" aria-label="Appointments pagination"><button :disabled="store.appointmentMeta.current_page<=1" @click="store.loadAppointments(store.appointmentMeta.current_page-1)">Previous</button><span>Page {{store.appointmentMeta.current_page}} of {{store.appointmentMeta.last_page}}</span><button :disabled="store.appointmentMeta.current_page>=store.appointmentMeta.last_page" @click="store.loadAppointments(store.appointmentMeta.current_page+1)">Next</button></nav>
    <section v-if="finishTarget" v-mobile-modal="() => finishTarget=null" class="sheet" role="dialog" aria-modal="true" aria-labelledby="finish-title"><header><div><p class="eyebrow">{{finishTarget.appointment_number}}</p><h2 id="finish-title">Finish treatment</h2></div><button aria-label="Close finish form" @click="finishTarget=null">×</button></header><form @submit.prevent="finish"><p><strong>{{finishTarget.customer?.name}}</strong><br>{{finishTarget.service?.name}}</p><label>Amount<input v-model="payment.amount" type="number" min="0" max="999999.99" step="0.01" required></label><label>Payment status<select v-model="payment.status"><option value="unpaid">Unpaid</option><option value="partial">Partially paid</option><option value="paid">Paid</option></select></label><label v-if="['partial','paid'].includes(payment.status)">Method<select v-model="payment.method"><option>Cash</option><option>GCash</option><option>Bank transfer</option><option>Other</option></select></label><label v-if="['partial','paid'].includes(payment.status)">Paid at<input v-model="payment.paidAt" type="datetime-local" required></label><label>Notes<textarea v-model="payment.notes" rows="3"></textarea></label><p v-if="store.error" class="alert" role="alert">{{Object.values(store.fields).flat()[0]??store.error}}</p><button class="primary" :disabled="store.working">{{store.working?'Finishing…':'Finish treatment'}}</button></form></section>
    <MobileConfirmDialog :open="!!noShowTarget" title="Mark as no-show?" :message="noShowTarget ? `Mark ${noShowTarget.appointment_number} as no-show?` : ''" confirm-label="Mark no-show" prompt-label="Reason (optional)" destructive @cancel="noShowTarget=null" @confirm="confirmNoShow" />
  </section>
</template>

<style scoped>
.page{width:min(100%,54rem);margin:auto;padding:max(1.25rem,env(safe-area-inset-top)) 1rem calc(6rem + env(safe-area-inset-bottom))}.page h1,.page h2,.sheet h2{font-family:var(--font-display);color:var(--casa-deep-palm)}.page header p{margin:.25rem 0}.summary{display:grid;grid-template-columns:repeat(3,1fr);margin:1rem 0;border:1px solid var(--casa-border);border-radius:var(--radius-operation);overflow:hidden;background:var(--casa-paper)}.summary span{display:grid;padding:.7rem .2rem;text-align:center;font-size:.7rem}.summary span+span{border-left:1px solid var(--casa-border)}.summary b{font-size:1rem;color:var(--casa-deep-palm)}.filters{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;margin-bottom:1rem}.filters input,.filters select,.filters button,.sheet input,.sheet select,.sheet textarea{width:100%;min-height:48px;border:1px solid var(--casa-border-strong);border-radius:var(--radius-control);background:#fff;padding:.65rem;font:inherit}.filters button{grid-column:1/-1;background:var(--casa-palm);color:#fff;font-weight:800}.notice{padding:.75rem;border-radius:var(--radius-control);background:var(--casa-success-bg);color:var(--casa-success)}.loading{text-align:center;padding:2rem}.list{display:grid;gap:.75rem}.card{padding:1rem;border:1px solid var(--casa-border);border-radius:var(--radius-operation);background:var(--casa-paper)}.card h2{margin:.6rem 0 .2rem;font-size:1.2rem}.card p{margin:.3rem 0;color:var(--casa-muted)}.top{display:flex;justify-content:space-between;gap:.5rem}.top small{padding:.2rem .5rem;border-radius:999px;background:var(--casa-success-bg);color:var(--casa-deep-palm)}.actions{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;margin-top:.8rem}.actions button,.pager button{min-height:48px;border:1px solid var(--casa-border);border-radius:var(--radius-control);background:#fff;color:var(--casa-deep-palm);font-weight:800}.actions .success{background:var(--casa-success-bg);border-color:var(--casa-palm)}.pager{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.5rem;margin-top:1rem}.pager span{text-align:center;font-size:.8rem;color:var(--casa-muted)}.empty{padding:1.5rem;text-align:center}.sheet{position:fixed;z-index:30;inset:0;overflow:auto;background:var(--casa-background);padding:max(1rem,env(safe-area-inset-top)) 1rem max(1rem,env(safe-area-inset-bottom))}.sheet>header,.sheet>form{max-width:40rem;margin:auto}.sheet>header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:1rem}.sheet>header button{width:48px;height:48px;border:1px solid var(--casa-border);border-radius:999px;background:#fff;font-size:1.5rem}.sheet>form{display:grid;gap:1rem;padding:1rem;border:1px solid var(--casa-border);border-radius:var(--radius-operation);background:var(--casa-paper)}.sheet label{font-weight:700}.sheet .primary{min-height:48px;border:0;border-radius:var(--radius-control);background:var(--casa-palm);color:#fff;font-weight:800}
</style>
