<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { formatAppointmentDate, formatPeso } from '../lib/appointments'
import { paymentStatusLabel } from '../lib/reception'
import { commissionRate, commissionStatusLabel } from '../lib/staff'
import { useStaffStore } from '../stores/staff'
import MobileSkeleton from '../components/MobileSkeleton.vue'
import { useInitialLoad } from '../composables/useInitialLoad'

const store=useStaffStore();const section=ref<'commissions'|'payments'>('commissions')
const { initialLoading, loadInitial } = useInitialLoad(() => store.hasCommissions())
onMounted(()=>void loadInitial(()=>store.loadCommissions()))
watch(section, value => { if(value==='payments') void store.loadTransactions() })
</script>

<template>
  <section class="page" aria-labelledby="earnings-title"><header><p class="eyebrow">Personal records</p><h1 id="earnings-title">Earnings & payments</h1><p>Commission payouts and payments related to your completed treatments are read-only.</p></header><div class="summary"><span><b>{{formatPeso(store.commissionSummary.pending)}}</b> Pending</span><span><b>{{formatPeso(store.commissionSummary.paid)}}</b> Paid out</span><span><b>{{formatPeso(store.commissionSummary.net)}}</b> Net</span></div><div class="switch"><button :class="{active:section==='commissions'}" @click="section='commissions'">Commissions</button><button :class="{active:section==='payments'}" @click="section='payments'">Payments</button></div>
    <p v-if="store.error" class="alert">{{store.error}}</p><MobileSkeleton v-if="initialLoading" variant="list" label="Loading earnings and payments" />
    <template v-else-if="section==='commissions'"><select v-model="store.commissionStatus" class="filter" aria-label="Commission status" @change="store.loadCommissions(1)"><option value="">All commission states</option><option value="pending">Pending payout</option><option value="paid">Paid out</option></select><div class="list"><article v-for="item in store.commissions" :key="item.id" class="card"><div class="top"><strong>{{formatPeso(item.amount)}}</strong><small>{{commissionStatusLabel(item.status)}}</small></div><h2>{{item.appointment?.service??'Commission adjustment'}}</h2><p>{{item.type==='earning'?`${commissionRate(item.rate)} of ${formatPeso(item.basis_amount)}`:'Reconciliation adjustment'}}</p><span>{{item.appointment?.appointment_number}} · {{formatAppointmentDate(item.earned_at)}}</span><p v-if="item.paid_at">Paid {{formatAppointmentDate(item.paid_at)}}</p></article><div v-if="!store.commissions.length" class="empty">No commission records found.</div></div><nav v-if="store.commissionMeta.last_page>1" class="pager"><button :disabled="store.commissionMeta.current_page<=1" @click="store.loadCommissions(store.commissionMeta.current_page-1)">Previous</button><span>Page {{store.commissionMeta.current_page}} of {{store.commissionMeta.last_page}}</span><button :disabled="store.commissionMeta.current_page>=store.commissionMeta.last_page" @click="store.loadCommissions(store.commissionMeta.current_page+1)">Next</button></nav></template>
    <template v-else><form class="filters" @submit.prevent="store.loadTransactions(1)"><input v-model="store.transactionSearch" placeholder="Payment or guest"><select v-model="store.transactionStatus"><option value="">All payment states</option><option value="unpaid">Unpaid</option><option value="partial">Partially paid</option><option value="paid">Paid</option><option value="refunded">Refunded</option><option value="void">Void</option></select><button>Apply</button></form><div class="list"><article v-for="item in store.transactions" :key="item.id" class="card"><div class="top"><strong>{{formatPeso(item.amount)}}</strong><small>{{paymentStatusLabel(item.payment_status)}}</small></div><h2>{{item.customer?.name}}</h2><p>{{item.service?.name}}</p><span>{{item.transaction_number}} · {{formatAppointmentDate(item.paid_at)}}</span></article><div v-if="!store.transactions.length" class="empty">No related payments found.</div></div></template>
  </section>
</template>

<style scoped>
.page{width:min(100%,54rem);margin:auto;padding:max(1.25rem,env(safe-area-inset-top)) 1rem calc(6rem + env(safe-area-inset-bottom))}.page h1,.page h2{font-family:Georgia,serif;color:#334736}.page header p{margin:.25rem 0}.summary{display:grid;grid-template-columns:repeat(3,1fr);margin:1rem 0;border:1px solid #dcd2c2;border-radius:1rem;overflow:hidden;background:#fffcf7}.summary span{display:grid;padding:.7rem .2rem;text-align:center;font-size:.7rem}.summary span+span{border-left:1px solid #dcd2c2}.summary b{font-size:.95rem;color:#334736}.switch{display:grid;grid-template-columns:1fr 1fr;gap:.4rem;padding:.3rem;margin-bottom:1rem;border:1px solid #dcd2c2;border-radius:.8rem;background:#fffcf7}.switch button{min-height:44px;border:0;border-radius:.6rem;background:transparent;font-weight:800;color:#67675f}.switch .active{background:#e9f2e8;color:#334736}.filter,.filters input,.filters select,.filters button{width:100%;min-height:48px;border:1px solid #bfb3a2;border-radius:.7rem;background:#fff;padding:.65rem;font:inherit}.filter{margin-bottom:1rem}.filters{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;margin-bottom:1rem}.filters button{grid-column:1/-1;background:#4f6a4e;color:#fff;font-weight:800}.loading{text-align:center;padding:2rem}.list{display:grid;gap:.65rem}.card{display:grid;gap:.3rem;padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7}.card h2{margin:.2rem 0;font-size:1.1rem}.card p,.card span{margin:.1rem 0;color:#67675f}.top{display:flex;justify-content:space-between;gap:.5rem}.top small{padding:.2rem .5rem;border-radius:999px;background:#e9f2e8;color:#334736}.pager{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.5rem;margin-top:1rem}.pager button{min-height:44px;border:1px solid #dcd2c2;border-radius:.7rem;background:#fff}.pager span{text-align:center;font-size:.8rem}.empty{padding:1.5rem;text-align:center}
</style>
