<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { formatAppointmentDate, formatPeso } from '../lib/appointments'
import { paymentStatusLabel } from '../lib/reception'
import { sentimentLabel } from '../lib/staff'
import { useStaffStore } from '../stores/staff'

const store=useStaffStore();const section=ref<'customers'|'feedback'>('customers')
onMounted(()=>Promise.all([store.loadCustomers(),store.loadFeedback()]))
</script>

<template>
  <section class="page" aria-labelledby="guests-title"><header><p class="eyebrow">Treatment context</p><h1 id="guests-title">Guests & feedback</h1><p>Only guests and reviews connected to your treatments are shown.</p></header><div class="switch"><button :class="{active:section==='customers'}" @click="section='customers'">Guests</button><button :class="{active:section==='feedback'}" @click="section='feedback'">Reviews</button></div>
    <p v-if="store.error" class="alert">{{store.error}}</p><div v-if="store.loading" class="loading">Loading guest records…</div>
    <template v-else-if="section==='customers'"><form class="filters" @submit.prevent="store.loadCustomers(1)"><input v-model="store.customerSearch" placeholder="Guest name, code, or phone"><button>Search</button></form><div class="list"><button v-for="guest in store.customers" :key="guest.id" class="card guest" @click="store.openCustomer(guest.id)"><strong>{{guest.name}}</strong><span>{{guest.customer_code}} · {{guest.phone??'No phone'}}</span><small>{{guest.assigned_appointments_count}} treatments with you</small></button><div v-if="!store.customers.length" class="empty">No guest records found.</div></div><nav v-if="store.customerMeta.last_page>1" class="pager"><button :disabled="store.customerMeta.current_page<=1" @click="store.loadCustomers(store.customerMeta.current_page-1)">Previous</button><span>Page {{store.customerMeta.current_page}} of {{store.customerMeta.last_page}}</span><button :disabled="store.customerMeta.current_page>=store.customerMeta.last_page" @click="store.loadCustomers(store.customerMeta.current_page+1)">Next</button></nav></template>
    <template v-else><form class="review-filters" @submit.prevent="store.loadFeedback(1)"><input v-model="store.feedbackSearch" placeholder="Guest or comment"><select v-model="store.feedbackSentiment"><option value="">All sentiments</option><option value="positive">Positive</option><option value="neutral">Neutral</option><option value="negative">Negative</option></select><button>Apply</button></form><div class="list"><article v-for="review in store.feedback" :key="review.id" class="card"><div class="top"><strong>{{'★'.repeat(review.rating)}}</strong><small :data-sentiment="review.sentiment">{{sentimentLabel(review.sentiment)}}</small></div><h2>{{review.customer?.name}}</h2><p>{{review.comment??'No written comment.'}}</p><span>{{review.service?.name}} · {{formatAppointmentDate(review.submitted_at)}}</span></article><div v-if="!store.feedback.length" class="empty">No feedback found.</div></div><nav v-if="store.feedbackMeta.last_page>1" class="pager"><button :disabled="store.feedbackMeta.current_page<=1" @click="store.loadFeedback(store.feedbackMeta.current_page-1)">Previous</button><span>Page {{store.feedbackMeta.current_page}} of {{store.feedbackMeta.last_page}}</span><button :disabled="store.feedbackMeta.current_page>=store.feedbackMeta.last_page" @click="store.loadFeedback(store.feedbackMeta.current_page+1)">Next</button></nav></template>
    <section v-if="store.selectedCustomer" class="sheet" role="dialog" aria-modal="true" aria-labelledby="guest-detail-title"><header><div><p class="eyebrow">{{store.selectedCustomer.customer_code}}</p><h2 id="guest-detail-title">{{store.selectedCustomer.name}}</h2></div><button aria-label="Close guest detail" @click="store.selectedCustomer=null">×</button></header><div class="detail"><section><h3>Contact & notes</h3><p>{{store.selectedCustomer.phone??'No phone'}} · {{store.selectedCustomer.email}}</p><p>{{store.selectedCustomer.address??'No address recorded.'}}</p><p><strong>Preference:</strong> {{store.selectedCustomer.contact_preference??'Not set'}}</p><p><strong>Operational notes:</strong> {{store.selectedCustomer.notes??'None'}}</p></section><section><h3>Treatment history with you</h3><article v-for="item in store.selectedCustomer.appointments" :key="item.id" class="history"><strong>{{item.service}}</strong><span>{{formatAppointmentDate(item.starts_at)}} · {{item.status.replace('_',' ')}}</span><small>{{item.appointment_number}}</small><p v-if="item.transaction">{{formatPeso(item.transaction.amount)}} · {{paymentStatusLabel(item.transaction.payment_status)}}</p><p v-if="item.feedback">{{'★'.repeat(item.feedback.rating)}} · {{item.feedback.comment??'No comment'}}</p></article></section></div></section>
  </section>
</template>

<style scoped>
.page{width:min(100%,54rem);margin:auto;padding:max(1.25rem,env(safe-area-inset-top)) 1rem calc(6rem + env(safe-area-inset-bottom))}.page h1,.page h2,.sheet h2,.sheet h3{font-family:Georgia,serif;color:#334736}.page header p{margin:.25rem 0}.switch{display:grid;grid-template-columns:1fr 1fr;gap:.4rem;padding:.3rem;margin:1rem 0;border:1px solid #dcd2c2;border-radius:.8rem;background:#fffcf7}.switch button{min-height:44px;border:0;border-radius:.6rem;background:transparent;font-weight:800;color:#67675f}.switch .active{background:#e9f2e8;color:#334736}.filters,.review-filters{display:grid;grid-template-columns:1fr auto;gap:.5rem;margin-bottom:1rem}.review-filters{grid-template-columns:1fr 1fr}.filters input,.filters button,.review-filters input,.review-filters select,.review-filters button{min-height:48px;border:1px solid #bfb3a2;border-radius:.7rem;background:#fff;padding:.65rem;font:inherit}.filters button,.review-filters button{background:#4f6a4e;color:#fff;font-weight:800}.review-filters button{grid-column:1/-1}.loading{text-align:center;padding:2rem}.list{display:grid;gap:.65rem}.card{display:grid;gap:.3rem;width:100%;padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7;color:#232620;text-align:left}.card h2{margin:.25rem 0;font-size:1.1rem}.card span,.card small,.card p{color:#67675f}.top{display:flex;justify-content:space-between}.top small{padding:.2rem .5rem;border-radius:999px;background:#e9f2e8}.pager{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.5rem;margin-top:1rem}.pager button{min-height:44px;border:1px solid #dcd2c2;border-radius:.7rem;background:#fff}.pager span{text-align:center;font-size:.8rem}.empty{padding:1.5rem;text-align:center}.sheet{position:fixed;z-index:30;inset:0;overflow:auto;background:#f5f0e7;padding:max(1rem,env(safe-area-inset-top)) 1rem max(1rem,env(safe-area-inset-bottom))}.sheet>header,.detail{max-width:42rem;margin:auto}.sheet>header{display:flex;justify-content:space-between}.sheet>header button{width:48px;height:48px;border:1px solid #dcd2c2;border-radius:999px;background:#fff;font-size:1.5rem}.detail{display:grid;gap:1rem}.detail>section{padding:1rem;border:1px solid #dcd2c2;border-radius:1rem;background:#fffcf7}.history{display:grid;gap:.2rem;padding:.75rem 0;border-top:1px solid #eee5d8}.history p{margin:.15rem 0;color:#67675f}
</style>
